import Link from 'next/link';
const pages: Record<string,{title:string;eyebrow:string;copy:string}> = {
  about:{eyebrow:'ABOUT US',title:'A corporate story built around quality.',copy:'This future-ready page is structured for verified NOVAQEN history, leadership, facilities, milestones and company information.'},
  manufacturing:{eyebrow:'MANUFACTURING & CAPABILITIES',title:'Capability with control at every step.',copy:'A dedicated future page for manufacturing workflows, equipment, capacity, packaging and operational capabilities.'},
  capabilities:{eyebrow:'CAPABILITIES',title:'Capability with control at every step.',copy:'A dedicated future page for manufacturing workflows, equipment, capacity, packaging and operational capabilities.'},
  quality:{eyebrow:'QUALITY ASSURANCE & CERTIFICATIONS',title:'Quality systems made visible.',copy:'Replace demo standards with verified GMP, ISO, regulatory and quality documentation supplied by NOVAQEN.'},
  gallery:{eyebrow:'GALLERY / FACTORY TOUR',title:'See the environment behind the work.',copy:'A full gallery and factory-tour experience can be connected to the landing-page lightbox and CMS gallery.'},
  research:{eyebrow:'RESEARCH & DEVELOPMENT',title:'From questions to better formulations.',copy:'A dedicated R&D page for formulation development, analytical workflows, laboratory capabilities and research updates.'},
  testimonials:{eyebrow:'REVIEWS / TESTIMONIALS',title:'Experiences, presented with context.',copy:'Connect verified testimonial JSON, video testimonials and approval workflows here.'},
  careers:{eyebrow:'CAREERS',title:'Build what comes next.',copy:'A careers experience ready for verified roles, culture, application forms and recruitment integrations.'},
  contact:{eyebrow:'CONTACT US',title:'Start a conversation.',copy:'The full contact page can reuse the secure enquiry workflow, map integration and document upload structure.'},
};
export default async function FuturePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const page=pages[slug]||{eyebrow:'NOVAQEN',title:'Future page ready.',copy:'This route is prepared for the full 10-page website.'};return <main style={{minHeight:'100svh',background:'linear-gradient(135deg,#041321,#0A2647)',color:'#fff',padding:'140px 7vw 90px',fontFamily:'Arial'}}><div style={{maxWidth:900}}><small style={{letterSpacing:4,color:'#72e1dc'}}>{page.eyebrow}</small><h1 style={{fontSize:'clamp(48px,8vw,96px)',lineHeight:.95,margin:'20px 0'}}>{page.title}</h1><p style={{fontSize:18,lineHeight:1.8,color:'#c7d7e1',maxWidth:700}}>{page.copy}</p><div style={{display:'flex',gap:12,marginTop:32,flexWrap:'wrap'}}><Link href="/" style={{padding:'14px 20px',borderRadius:999,background:'#2AB7B7',color:'#041321',fontWeight:800}}>Back to home</Link><Link href="/contact" style={{padding:'14px 20px',borderRadius:999,border:'1px solid #ffffff44'}}>Contact / Partner</Link></div></div></main>}
